services:
  web:
    build: .
    container_name: backend_lab2_app
    ports:
      - "8000:8000"
    # Mount project directory into container. Remove :ro to allow live-reload during development.
    volumes:
      - ./:/app
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped